### PR TITLE
README.txt: Rewrite to Markdown syntax

### PR DESCRIPTION
**Pull request by erikbgithub**
I thought you might consider adapting your Readme to a format that Github can parse. This way you have more power over how your Readme is presented to the public. Have a look [at my fork](https://github.com/erikb85/java-simple-serial-connector), if you want to see how it looks. It's the same syntax used for comments _like this one_ by the way.

Of course changes to this pull request are still possible.

### CODE REVIEW

**Comment by scream3r** [comment]
Thank you for your work, I had no time for this at last week, I worked on a new 2.5.0 release. Now I can try to make the project description more pretty =)

**Comment by erikbgithub** [comment]
It's okay. That's the good thing about open source. Everybody contributes what he can. Continue focus on the code. :)

But why didn't you merge it?

**Comment by scream3r** [comment]
I want to clear this readme. This file is a part of release archives and I don't think that should place it on a main project page.

**Comment by erikbgithub** [comment]
Ah, I see. Many projects structure their folders like that:

```
<main-folder>/
   CHANGES.txt # change hsitory
   doc/        # static pages for the documentation and/or markup stuff
   LICENSE.txt # something like the `GPL v3 or later` text
   README.txt  # project goals, requriements for usage, short tutorial
   src/        # the code
   test/       # unit-test suites
```

So in my eyes it's not bad to have the changes in the main folder.

If I can help one way or another, @ me in an Issue or write me a private message.

**Pull request closed without merging**
